package com.techedge.ias.data.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "InvestmentPortfolio")
public class InvestmentPortfolio {


    private String transactionID;
    private String customerID;
    private String accountID;
    private String accountName;
    private String ticker;
    private String investment_type;
    private double purchase_price;
    private int number_of_shares;
    private String purchase_date;

    public InvestmentPortfolio() {
    }

    public InvestmentPortfolio(String customerID, String accountID) {
        this.customerID = customerID;
        this.accountID = accountID;
    }

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getTransactionID() {
        return transactionID;
    }

    public void setTransactionID(String transactionID) {
        this.transactionID = transactionID;
    }


    @DynamoDBAttribute
    public String getCustomerID() {
        return customerID;
    }

    public void setCustomerID(String customerID) {
        this.customerID = customerID;
    }

    @DynamoDBAttribute
    public String getAccountID() {
        return accountID;
    }

    public void setAccountID(String accountID) {
        this.accountID = accountID;
    }

    @DynamoDBAttribute
    public String getAccountName() {
        return accountName;
    }

    public void setAccountName(String accountName) {
        this.accountName = accountName;
    }

    @DynamoDBAttribute
    public String getTicker() {
        return ticker;
    }

    public void setTicker(String ticker) {
        this.ticker = ticker;
    }

    @DynamoDBAttribute
    public String getInvestment_type() {
        return investment_type;
    }

    public void setInvestment_type(String investment_type) {
        this.investment_type = investment_type;
    }

    @DynamoDBAttribute
    public double getPurchase_price() {
        return purchase_price;
    }

    public void setPurchase_price(double purchase_price) {
        this.purchase_price = purchase_price;
    }

    @DynamoDBAttribute
    public int getNumber_of_shares() {
        return number_of_shares;
    }

    public void setNumber_of_shares(int number_of_shares) {
        this.number_of_shares = number_of_shares;
    }

    @DynamoDBAttribute
    public String getPurchase_date() {
        return purchase_date;
    }

    public void setPurchase_date(String purchase_date) {
        this.purchase_date = purchase_date;
    }
}
